version: '3'
services:
  backend:
    build:
      context: ../Backend/backend  # Указываем правильный путь к папке backend
    container_name: backend
    volumes:
      - ../Backend/backend/data.txt:/app/data.txt  # Монтируем файл данных с правильным путем
    networks:
      - app-network
    restart: always
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../Frontend/frontend/frontend  # Указываем правильный путь к папке frontend
    container_name: frontend
    networks:
      - app-network
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
